config/routes.rb
Rails.application.routes.draw do
  resources :quote_categories
  resources :categories
  resources :quotes
  resources :philosophers
  resources :users
  
  root 'home#index'
  get '/about', to: 'about#index'
  get 'search', to: 'search#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get '/admin', to: 'home#aindex'
  get '/userhome', to: 'home#uindex'

  get '/your-quotes', to: 'home#uquotes'
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/search">Search</a>
        </li>
        <li class="nav-item">
          <%= link_to 'About Us', about_path, class:"nav-link" %>
        </li>
        <!-- Sign Up link: -->
        <% if !logged_in? %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_path, class:"nav-link" %>
          </li>
        <% end %>
        <!-- Sign In link: -->
        <% if !logged_in? %>
          <li class="nav-item">
            <%= link_to 'Sign In', login_path, class:"nav-link" %>
          </li>
        <% end %>
        <!-- Sign Out link: -->
        <% if logged_in? %>
          <li class="nav-item">
            <%= button_to "Sign Out", logout_path, method: :delete, class:"btn btn-link nav-link" %>
          </li>
        <% end %>

        <% if logged_in? && !is_administrator? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">My Account</a></li>
            <!-- Link to the "My Quotes" page for logged-in users -->
            <li><%= link_to 'My Quotes', your_quotes_path, class: 'dropdown-item' %></li>
            <li><hr class="dropdown-divider"></li>
            <!-- Link to the "Add New Quote" form -->
            <li><%= link_to 'Add New Quote', new_quote_path, class: 'dropdown-item' %></li>
          </ul>
        </li>
        <% end %>

        <% if logged_in? && is_administrator? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Admin
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Admin Home</a></li>
            <li><%= link_to 'Manage Users', users_path, class:"dropdown-item" %></li>
          </ul>
        </li>
        <% end %>
        
      </ul>
      
      <!-- Commenting out the search form at the bottom -->
      <!-- 
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      -->

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyQuote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    
  </head>

  <body>

  <div class="container" style="margin-top:20px;">
  <%= render 'layouts/header' %>
  <%= yield %>
  </div>

  </body>
</html>